const ACTIONS = {
    // auth
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOGOUT: 'LOGOUT',

    // group
    CREATE_GROUP: 'CREATE_GROUP',
    GET_GROUP: 'GET_GROUP',
    SEARCH_GROUP: 'SEARCH_GROUP',
    NOTIFICATION: 'NOTIFICATION'
};

export default ACTIONS;
